baseURL = "https://ericyawilhit.netlify.app"
languageCode = "fr"
title = "Eric Yawilhit"
theme = "PaperMod"

[params]
  author = "Eric Yawilhit"
  description = "J'apprends, je construis, je documente — PKI pour l'Afrique"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  images = ["images/Eric Yawilhit.png"]
  ShowToc = true
  ShowCodeCopyButtons = true
  comment = true 
  system = "giscus"

[[param.giscus]]
  repo = "Brizman236/ericyawilhit"
  repoId = "R_kgDORpa0mw"
  category = "Announcements"
  categoryID = "DIC_kwDORpa0m84C4wiQ"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "top"
  theme = "preferred_color_scheme"
  lang = "fr"

[params.profileMode]
  enabled = true
  title = "Eric Yawilhit"
  subtitle = "J'apprends, je construis, je documente — PKI pour l'Afrique."
  imageUrl = "/images/avatar.jpeg"
  imageTitle = "Eric Yawilhit"

[params.homeInfoParams]
  Title = "Eric Yawilhit"
  Content = "J'apprends, je construis, je documente — PKI pour l'Afrique."

[menu]
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 2

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/eric-yawilhit"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Brizman236"